spring:
  application:
    name: zuul-service

server:
  port: 9000

#zuul:
#  routes:
#    blog:
#        path: /hks/**
#        url: https://blog.csdn.net/singgel/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api:
        path: /**
        serviceId: eureka-provider